### ISSUE TITLE
Permissions notifications have missing text

### ISSUE THREAD

**Issue by onlytruejames** [skyebrowser/skye#10]
**Bug description**
Permissions notifications have missing text. It should say {site} wants to: {permissions} but the only displayed text is "wants to:"
**To Reproduce**
Go on a site that asks for a permission
**Screenshots**
![image](https://user-images.githubusercontent.com/59912615/143496602-64418cca-f8fd-467b-a855-b88d3c465eb4.png)
**Details:**
- Operating System: Ubuntu 21.04
- Skye version: 6.0.4
- Last known working Skye version: 6.0.4

Keep up the good work :)

**Comment by A-da-m** [comment]
Resolved in v6.0.8
