### ISSUE TITLE
Make tabs not work like old mobile Safari please god I'm begging you

### ISSUE THREAD

**Issue by jadeastar** [skyebrowser/skye#13]
**Is your feature request related to a problem? Please describe.**

When opening a new tab, it switches to that new tab. This is incredibly annoying.

**Describe the solution you'd like**

Make tabs open in the background.

**Describe alternatives you've considered**

There is no option

**Additional context**

**Comment by lleyton** [comment]
alrightie <3

**Comment by lleyton** [comment]
Looks like the issue with implementing foreground tabs is an issue that we encountered in electron-browser-extensions. Specifically [this line](https://github.com/samuelmaddock/electron-browser-shell/blob/c47bcb3c7a1ff274b469ecffb25245cf580e5811/packages/electron-chrome-extensions/src/browser/api/tabs.ts#L70), which doesn't check if the tab is "active" before calling the method to select it.

Mitigations:
1. Work around it somehow. (Couldn't find a way to do that yet...)
2. Work with the upstream maintainer
3. Fork it

**Comment by lleyton** [comment]
yeah, I didn't really want to fork anything, so I just used patch-package
