### ISSUE TITLE
Don't set DNT to True by default, and use GPC instead

### ISSUE THREAD

**Issue by jamiethalacker** [skyebrowser/skye#14]
**Is your feature request related to a problem? Please describe.**
Do Not Track has been described as a "failed experiment," and was never really honoured by most advertising networks<sup>[1]</sup>, and in some cases, can make you *more* prone to being fingerprinted (it's a separate header that can be used to generate a more unique browser fingerprint.)

**Describe the solution you'd like**
Disable DNT by default. It should still be available as an option, but not set to On by default

**Describe alternatives you've considered**
Global Privacy Control (GPC), a new standard started in 2020 by many different privacy researchers and companies, including the EFF and Automattic.<sup>[2]</sup> According to the California Consumer Privacy Act, GPC is considered a valid Do Not Sell My Personal Information signal, and legally must be respected.<sup>[3]</sup>.

For more information on GPC, visit https://globalprivacycontrol.org/.

**Additional context**

<sup>1</sup> https://en.wikipedia.org/wiki/Do_Not_Track#Adoption
<sup>2</sup> https://en.wikipedia.org/wiki/Do_Not_Track#Global_Privacy_Control
<sup>3</sup> https://oag.ca.gov/privacy/ccpa

**Comment by lleyton** [comment]
Added it, will close issue when a release is made
