### ISSUE TITLE
Incorrect title for some Innatical sites

### ISSUE THREAD

**Issue by niilasoika** [skyebrowser/skye#4]
**Bug description**

When I open https://id.innatical.com or https://skye.innatical.com, the title of both sites is "New tab" all of the time.

**To Reproduce**
Go to id.innatical.com or skye.innatical.com using Skye.

**Expected behavior**
I excepted the title to be the same as with any other browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/43517893/140601465-66b29dba-0ebd-45f8-8d48-de1e521f4816.png)
![image](https://user-images.githubusercontent.com/43517893/140601473-9769acdf-bf65-4e3c-bfaa-27300d81b5ab.png)

**Details:**

- Operating System: Windows 11 22000.258
- Skye version: 6.0.4
- Last known working Skye version: N/A

**Additional context**

With title I mean the site name appearing in the tab bar.

**Comment by lleyton** [comment]
Fixed in v6.2.0
