### ISSUE TITLE
Issues with Installation in base on tauOS

### ISSUE THREAD

**Issue by jadeastar** [skyebrowser/skye#40]
# Skye installs to `/opt` which causes issues with OSTree.

## Possible solutions:
- Create Skye Flatpak.
- Change RPM installation location to another directory.

[tauOS Sourceview Issue](https://sourceview.innatical.com/tauos/meta/-/issues/7)

**Comment by lleyton** [comment]
Non-issue now, the latest Skye RPM layers and launches properly on OSTree. A flatpak would be nice to support however.

**Comment by jadeastar** [comment]
Regressed
[tauOS Sourceview Issue](https://sourceview.innatical.com/tauos/meta/-/issues/7)
