### ISSUE TITLE
Main browser buttons, Skye version

### ISSUE THREAD

**Issue by piksileee** [skyebrowser/skye#6]
**Bug description**

1. So if you try using light mode, you won't be able to see close, windows and minimize buttons
2. You can't check Skye version

**To Reproduce**

1. Just open a tab while light mode is on

**Expected behavior**

While on light mode, those buttons should be black, or same color as other texts

**Screenshots**

![image](https://user-images.githubusercontent.com/88730319/141830132-0f44b48b-64c4-4f9a-94b4-c822ebb4e078.png)
![image](https://user-images.githubusercontent.com/88730319/141830218-7d4b566e-4496-4765-ab69-9ffb19c450dc.png)

**Details:**

- Operating System: Windows 10 Pro
- Skye version: Latest
- Last known working Skye version: Latest

**Comment by A-da-m** [comment]
Resolved in v6.0.8
