### ISSUE TITLE
Animated top bar + Developer terminal/cmd prompt

### ISSUE THREAD

**Issue by piksileee** [skyebrowser/skye#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We should add animated top bar, when we close all the tabs instead of just spawning the bar there, we should animate it.
Also we should add like a terminal on the website for the developers, like an icon where the settings button is, in the settings page we should add a developer section and while its enabled you could use terminal/cmd prompt so we can use it for some things

**Comment by A-da-m** [comment]
I assume by terminal/cmd prompt you mean inspect element?

**Comment by piksileee** [comment]
> I assume by terminal/cmd prompt you mean inspect element?

No, not really. In settings there should maybe be developer options that if we enable the cmd promt/terminal icons shows next to the settings button on the browser, so we can access something like a host console, when we try to host our website. Basically when we host a website and open local host, we can connect our normal console with that console, so we can see detailed errors + execute cmds
