### ISSUE TITLE
Menus do not close

### ISSUE THREAD

**Issue by onlytruejames** [skyebrowser/skye#9]
**Bug description**
Menus do not close when you click anywhere other than the website, so if you have the address bar open you can't close it when you click next to the bar
**To Reproduce**
Click on the address bar then click next to the address bar 
**Expected behavior**
A user would expect the address bar to close
**Details:**
- Operating System: Ubuntu 21.04
- Skye version: 6.0.4
- Last known working Skye version:
 6.0.4

**Comment by jadeastar** [comment]
Same issue on Fedora 35 with the RPM

**Comment by lleyton** [comment]
Fixed, going to be released soon :)
